import{j as n}from"./jsx-runtime.D_zvdyIk.js";
import{P as y,u as A,a as Ee,b as oe,c as be,d as re,e as F,f as S,g as ae,h as b,i as ye,D as Ie,j as V,k as Z,R as Te,C as je}from"./ChevronIcon.CantmlAf.js";
import{r as s}from"./index.DIWIMQJi.js";
import{u as Pe}from"./index.CQqkad0s.js";
import"./index.DQSunKuR.js";
var _e=Object.freeze({position:"absolute",border:0,width:1,height:1,padding:0,margin:-1,overflow:"hidden",clip:"rect(0, 0, 0, 0)",whiteSpace:"nowrap",wordWrap:"normal"}),Se="VisuallyHidden",ie=s.forwardRef((e,t)=>n.jsx(y.span,{...e,ref:t,style:{..._e,...e.style}}));
ie.displayName=Se;
var De=ie,D="NavigationMenu",[$,se,ke]=re(D),[z,Ae,Le]=re(D),[Y,ut]=be(D,[ke,Le]),[Oe,I]=Y(D),[Fe,Ke]=Y(D),ce=s.forwardRef((e,t)=>{const{__scopeNavigationMenu:o,value:r,onValueChange:a,defaultValue:i,delayDuration:c=200,skipDelayDuration:d=300,orientation:l="horizontal",dir:x,...u}=e,[g,M]=s.useState(null),R=A(t,C=>M(C)),p=Ee(x),h=s.useRef(0),N=s.useRef(0),E=s.useRef(0),[T,v]=s.useState(!0),[m,f]=oe({prop:r,onChange:C=>{const P=C!=="",K=d>0;
P?(window.clearTimeout(E.current),K&&v(!1)):(window.clearTimeout(E.current),E.current=window.setTimeout(()=>v(!0),d)),a?.(C)},defaultProp:i??"",caller:D}),w=s.useCallback(()=>{window.clearTimeout(N.current),N.current=window.setTimeout(()=>f(""),150)},[f]),j=s.useCallback(C=>{window.clearTimeout(N.current),f(C)},[f]),_=s.useCallback(C=>{m===C?window.clearTimeout(N.current):h.current=window.setTimeout(()=>{window.clearTimeout(N.current),f(C)},c)},[m,f,c]);
return s.useEffect(()=>()=>{window.clearTimeout(h.current),window.clearTimeout(N.current),window.clearTimeout(E.current)},[]),n.jsx(ue,{scope:o,isRootMenu:!0,value:m,dir:p,orientation:l,rootNavigationMenu:g,onTriggerEnter:C=>{window.clearTimeout(h.current),T?_(C):j(C)},onTriggerLeave:()=>{window.clearTimeout(h.current),w()},onContentEnter:()=>window.clearTimeout(N.current),onContentLeave:w,onItemSelect:C=>{f(P=>P===C?"":C)},onItemDismiss:()=>f(""),children:n.jsx(y.nav,{"aria-label":"Main","data-orientation":l,dir:p,...u,ref:R})})});
ce.displayName=D;
var G="NavigationMenuSub",Ve=s.forwardRef((e,t)=>{const{__scopeNavigationMenu:o,value:r,onValueChange:a,defaultValue:i,orientation:c="horizontal",...d}=e,l=I(G,o),[x,u]=oe({prop:r,onChange:a,defaultProp:i??"",caller:G});
return n.jsx(ue,{scope:o,isRootMenu:!1,value:x,dir:l.dir,orientation:c,rootNavigationMenu:l.rootNavigationMenu,onTriggerEnter:g=>u(g),onItemSelect:g=>u(g),onItemDismiss:()=>u(""),children:n.jsx(y.div,{"data-orientation":c,...d,ref:t})})});
Ve.displayName=G;
var ue=e=>{const{scope:t,isRootMenu:o,rootNavigationMenu:r,dir:a,orientation:i,children:c,value:d,onItemSelect:l,onItemDismiss:x,onTriggerEnter:u,onTriggerLeave:g,onContentEnter:M,onContentLeave:R}=e,[p,h]=s.useState(null),[N,E]=s.useState(new Map),[T,v]=s.useState(null);
return n.jsx(Oe,{scope:t,isRootMenu:o,rootNavigationMenu:r,value:d,previousValue:Pe(d),baseId:ae(),dir:a,orientation:i,viewport:p,onViewportChange:h,indicatorTrack:T,onIndicatorTrackChange:v,onTriggerEnter:S(u),onTriggerLeave:S(g),onContentEnter:S(M),onContentLeave:S(R),onItemSelect:S(l),onItemDismiss:S(x),onViewportContentChange:s.useCallback((m,f)=>{E(w=>(w.set(m,f),new Map(w)))},[]),onViewportContentRemove:s.useCallback(m=>{E(f=>f.has(m)?(f.delete(m),new Map(f)):f)},[]),children:n.jsx($.Provider,{scope:t,children:n.jsx(Fe,{scope:t,items:N,children:c})})})},le="NavigationMenuList",de=s.forwardRef((e,t)=>{const{__scopeNavigationMenu:o,...r}=e,a=I(le,o),i=n.jsx(y.ul,{"data-orientation":a.orientation,...r,ref:t});
return n.jsx(y.div,{style:{position:"relative"},ref:a.onIndicatorTrackChange,children:n.jsx($.Slot,{scope:o,children:a.isRootMenu?n.jsx(Ce,{asChild:!0,children:i}):i})})});
de.displayName=le;
var ve="NavigationMenuItem",[ze,fe]=Y(ve),ge=s.forwardRef((e,t)=>{const{__scopeNavigationMenu:o,value:r,...a}=e,i=ae(),c=r||i||"LEGACY_REACT_AUTO_VALUE",d=s.useRef(null),l=s.useRef(null),x=s.useRef(null),u=s.useRef(()=>{}),g=s.useRef(!1),M=s.useCallback((p="start")=>{if(d.current){u.current();
const h=H(d.current);
h.length&&J(p==="start"?h:h.reverse())}},[]),R=s.useCallback(()=>{if(d.current){const p=H(d.current);
p.length&&(u.current=qe(p))}},[]);
return n.jsx(ze,{scope:o,value:c,triggerRef:l,contentRef:d,focusProxyRef:x,wasEscapeCloseRef:g,onEntryKeyDown:M,onFocusProxyEnter:M,onRootContentClose:R,onContentFocusOutside:R,children:n.jsx(y.li,{...a,ref:t})})});
ge.displayName=ve;
var U="NavigationMenuTrigger",me=s.forwardRef((e,t)=>{const{__scopeNavigationMenu:o,disabled:r,...a}=e,i=I(U,e.__scopeNavigationMenu),c=fe(U,e.__scopeNavigationMenu),d=s.useRef(null),l=A(d,c.triggerRef,t),x=Me(i.baseId,c.value),u=Re(i.baseId,c.value),g=s.useRef(!1),M=s.useRef(!1),R=c.value===i.value;
return n.jsxs(n.Fragment,{children:[n.jsx($.ItemSlot,{scope:o,value:c.value,children:n.jsx(Ne,{asChild:!0,children:n.jsx(y.button,{id:x,disabled:r,"data-disabled":r?"":void 0,"data-state":Q(R),"aria-expanded":R,"aria-controls":u,...a,ref:l,onPointerEnter:b(e.onPointerEnter,()=>{M.current=!1,c.wasEscapeCloseRef.current=!1}),onPointerMove:b(e.onPointerMove,O(()=>{r||M.current||c.wasEscapeCloseRef.current||g.current||(i.onTriggerEnter(c.value),g.current=!0)})),onPointerLeave:b(e.onPointerLeave,O(()=>{r||(i.onTriggerLeave(),g.current=!1)})),onClick:b(e.onClick,()=>{i.onItemSelect(c.value),M.current=R}),onKeyDown:b(e.onKeyDown,p=>{const N={horizontal:"ArrowDown",vertical:i.dir==="rtl"?"ArrowLeft":"ArrowRight"}[i.orientation];
R&&p.key===N&&(c.onEntryKeyDown(),p.preventDefault())})})})}),R&&n.jsxs(n.Fragment,{children:[n.jsx(De,{"aria-hidden":!0,tabIndex:0,ref:c.focusProxyRef,onFocus:p=>{const h=c.contentRef.current,N=p.relatedTarget,E=N===d.current,T=h?.contains(N);
(E||!T)&&c.onFocusProxyEnter(E?"start":"end")}}),i.viewport&&n.jsx("span",{"aria-owns":u})]})]})});
me.displayName=U;
var Ge="NavigationMenuLink",ee="navigationMenu.linkSelect",pe=s.forwardRef((e,t)=>{const{__scopeNavigationMenu:o,active:r,onSelect:a,...i}=e;
return n.jsx(Ne,{asChild:!0,children:n.jsx(y.a,{"data-active":r?"":void 0,"aria-current":r?"page":void 0,...i,ref:t,onClick:b(e.onClick,c=>{const d=c.target,l=new CustomEvent(ee,{bubbles:!0,cancelable:!0});
if(d.addEventListener(ee,x=>a?.(x),{once:!0}),Z(d,l),!l.defaultPrevented&&!c.metaKey){const x=new CustomEvent(L,{bubbles:!0,cancelable:!0});
Z(d,x)}},{checkForDefaultPrevented:!1})})})});
pe.displayName=Ge;
var q="NavigationMenuIndicator",Ue=s.forwardRef((e,t)=>{const{forceMount:o,...r}=e,a=I(q,e.__scopeNavigationMenu),i=!!a.value;
return a.indicatorTrack?Te.createPortal(n.jsx(F,{present:o||i,children:n.jsx(He,{...r,ref:t})}),a.indicatorTrack):null});
Ue.displayName=q;
var He=s.forwardRef((e,t)=>{const{__scopeNavigationMenu:o,...r}=e,a=I(q,o),i=se(o),[c,d]=s.useState(null),[l,x]=s.useState(null),u=a.orientation==="horizontal",g=!!a.value;
s.useEffect(()=>{const p=i().find(h=>h.value===a.value)?.ref.current;
p&&d(p)},[i,a.value]);
const M=()=>{c&&x({size:u?c.offsetWidth:c.offsetHeight,offset:u?c.offsetLeft:c.offsetTop})};
return W(c,M),W(a.indicatorTrack,M),l?n.jsx(y.div,{"aria-hidden":!0,"data-state":g?"visible":"hidden","data-orientation":a.orientation,...r,ref:t,style:{position:"absolute",...u?{left:0,width:l.size+"px",transform:`translateX(${l.offset}px)`}:{top:0,height:l.size+"px",transform:`translateY(${l.offset}px)`},...r.style}}):null}),k="NavigationMenuContent",he=s.forwardRef((e,t)=>{const{forceMount:o,...r}=e,a=I(k,e.__scopeNavigationMenu),i=fe(k,e.__scopeNavigationMenu),c=A(i.contentRef,t),d=i.value===a.value,l={value:i.value,triggerRef:i.triggerRef,focusProxyRef:i.focusProxyRef,wasEscapeCloseRef:i.wasEscapeCloseRef,onContentFocusOutside:i.onContentFocusOutside,onRootContentClose:i.onRootContentClose,...r};
return a.viewport?n.jsx(We,{forceMount:o,...l,ref:c}):n.jsx(F,{present:o||d,children:n.jsx(we,{"data-state":Q(d),...l,ref:c,onPointerEnter:b(e.onPointerEnter,a.onContentEnter),onPointerLeave:b(e.onPointerLeave,O(a.onContentLeave)),style:{pointerEvents:!d&&a.isRootMenu?"none":void 0,...l.style}})})});
he.displayName=k;
var We=s.forwardRef((e,t)=>{const o=I(k,e.__scopeNavigationMenu),{onViewportContentChange:r,onViewportContentRemove:a}=o;
return V(()=>{r(e.value,{ref:t,...e})},[e,t,r]),V(()=>()=>a(e.value),[e.value,a]),null}),L="navigationMenu.rootContentDismiss",we=s.forwardRef((e,t)=>{const{__scopeNavigationMenu:o,value:r,triggerRef:a,focusProxyRef:i,wasEscapeCloseRef:c,onRootContentClose:d,onContentFocusOutside:l,...x}=e,u=I(k,o),g=s.useRef(null),M=A(g,t),R=Me(u.baseId,r),p=Re(u.baseId,r),h=se(o),N=s.useRef(null),{onItemDismiss:E}=u;
s.useEffect(()=>{const v=g.current;
if(u.isRootMenu&&v){const m=()=>{E(),d(),v.contains(document.activeElement)&&a.current?.focus()};
return v.addEventListener(L,m),()=>v.removeEventListener(L,m)}},[u.isRootMenu,e.value,a,E,d]);
const T=s.useMemo(()=>{const m=h().map(P=>P.value);
u.dir==="rtl"&&m.reverse();
const f=m.indexOf(u.value),w=m.indexOf(u.previousValue),j=r===u.value,_=w===m.indexOf(r);
if(!j&&!_)return N.current;
const C=(()=>{if(f!==w){if(j&&w!==-1)return f>w?"from-end":"from-start";
if(_&&f!==-1)return f>w?"to-start":"to-end"}return null})();
return N.current=C,C},[u.previousValue,u.value,u.dir,h,r]);
return n.jsx(Ce,{asChild:!0,children:n.jsx(Ie,{id:p,"aria-labelledby":R,"data-motion":T,"data-orientation":u.orientation,...x,ref:M,disableOutsidePointerEvents:!1,onDismiss:()=>{const v=new Event(L,{bubbles:!0,cancelable:!0});
g.current?.dispatchEvent(v)},onFocusOutside:b(e.onFocusOutside,v=>{l();
const m=v.target;
u.rootNavigationMenu?.contains(m)&&v.preventDefault()}),onPointerDownOutside:b(e.onPointerDownOutside,v=>{const m=v.target,f=h().some(j=>j.ref.current?.contains(m)),w=u.isRootMenu&&u.viewport?.contains(m);
(f||w||!u.isRootMenu)&&v.preventDefault()}),onKeyDown:b(e.onKeyDown,v=>{const m=v.altKey||v.ctrlKey||v.metaKey;
if(v.key==="Tab"&&!m){const w=H(v.currentTarget),j=document.activeElement,_=w.findIndex(K=>K===j),P=v.shiftKey?w.slice(0,_).reverse():w.slice(_+1,w.length);
J(P)?v.preventDefault():i.current?.focus()}}),onEscapeKeyDown:b(e.onEscapeKeyDown,v=>{c.current=!0})})})}),X="NavigationMenuViewport",xe=s.forwardRef((e,t)=>{const{forceMount:o,...r}=e,i=!!I(X,e.__scopeNavigationMenu).value;
return n.jsx(F,{present:o||i,children:n.jsx(Be,{...r,ref:t})})});
xe.displayName=X;
var Be=s.forwardRef((e,t)=>{const{__scopeNavigationMenu:o,children:r,...a}=e,i=I(X,o),c=A(t,i.onViewportChange),d=Ke(k,e.__scopeNavigationMenu),[l,x]=s.useState(null),[u,g]=s.useState(null),M=l?l?.width+"px":void 0,R=l?l?.height+"px":void 0,p=!!i.value,h=p?i.value:i.previousValue;
return W(u,()=>{u&&x({width:u.offsetWidth,height:u.offsetHeight})}),n.jsx(y.div,{"data-state":Q(p),"data-orientation":i.orientation,...a,ref:c,style:{pointerEvents:!p&&i.isRootMenu?"none":void 0,"--radix-navigation-menu-viewport-width":M,"--radix-navigation-menu-viewport-height":R,...a.style},onPointerEnter:b(e.onPointerEnter,i.onContentEnter),onPointerLeave:b(e.onPointerLeave,O(i.onContentLeave)),children:Array.from(d.items).map(([E,{ref:T,forceMount:v,...m}])=>{const f=h===E;
return n.jsx(F,{present:v||f,children:n.jsx(we,{...m,ref:ye(T,w=>{f&&w&&g(w)})})},E)})})}),$e="FocusGroup",Ce=s.forwardRef((e,t)=>{const{__scopeNavigationMenu:o,...r}=e,a=I($e,o);
return n.jsx(z.Provider,{scope:o,children:n.jsx(z.Slot,{scope:o,children:n.jsx(y.div,{dir:a.dir,...r,ref:t})})})}),te=["ArrowRight","ArrowLeft","ArrowUp","ArrowDown"],Ye="FocusGroupItem",Ne=s.forwardRef((e,t)=>{const{__scopeNavigationMenu:o,...r}=e,a=Ae(o),i=I(Ye,o);
return n.jsx(z.ItemSlot,{scope:o,children:n.jsx(y.button,{...r,ref:t,onKeyDown:b(e.onKeyDown,c=>{if(["Home","End",...te].includes(c.key)){let l=a().map(g=>g.ref.current);
if([i.dir==="rtl"?"ArrowRight":"ArrowLeft","ArrowUp","End"].includes(c.key)&&l.reverse(),te.includes(c.key)){const g=l.indexOf(c.currentTarget);
l=l.slice(g+1)}setTimeout(()=>J(l)),c.preventDefault()}})})})});
function H(e){const t=[],o=document.createTreeWalker(e,NodeFilter.SHOW_ELEMENT,{acceptNode:r=>{const a=r.tagName==="INPUT"&&r.type==="hidden";
return r.disabled||r.hidden||a?NodeFilter.FILTER_SKIP:r.tabIndex>=0?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_SKIP}});
for(;
o.nextNode();
)t.push(o.currentNode);
return t}function J(e){const t=document.activeElement;
return e.some(o=>o===t?!0:(o.focus(),document.activeElement!==t))}function qe(e){return e.forEach(t=>{t.dataset.tabindex=t.getAttribute("tabindex")||"",t.setAttribute("tabindex","-1")}),()=>{e.forEach(t=>{const o=t.dataset.tabindex;
t.setAttribute("tabindex",o)})}}function W(e,t){const o=S(t);
V(()=>{let r=0;
if(e){const a=new ResizeObserver(()=>{cancelAnimationFrame(r),r=window.requestAnimationFrame(o)});
return a.observe(e),()=>{window.cancelAnimationFrame(r),a.unobserve(e)}}},[e,o])}function Q(e){return e?"open":"closed"}function Me(e,t){return`${e}-trigger-${t}`}function Re(e,t){return`${e}-content-${t}`}function O(e){return t=>t.pointerType==="mouse"?e(t):void 0}var Xe=ce,Je=de,ne=ge,Qe=me,B=pe,Ze=he,et=xe;
function lt({navMenuItems:e}){return n.jsxs(Xe,{children:[n.jsx(Je,{className:"nav-menu-list",children:e.map(t=>n.jsx(tt,{item:t},t.label))}),n.jsx("div",{className:"nav-menu-viewport-position",children:n.jsx(et,{className:"nav-menu-viewport"})})]})}function tt({item:e}){const t=e.label.toLowerCase().replace(/\s+/g,"-");
return e.href?n.jsx(ne,{className:"nav-menu-item",value:t,children:n.jsx(B,{href:e.href,className:"nav-menu-link","data-astro-prefetch":e.prefetch,children:e.label})}):n.jsxs(ne,{className:"nav-menu-item",value:t,children:[n.jsxs(Qe,{className:"nav-menu-trigger",children:[e.label,e.sections&&n.jsx(je,{})]}),e.sections&&n.jsx(Ze,{className:"nav-menu-content",children:e.sections.map((o,r)=>n.jsx(nt,{section:o},r))})]})}function nt({section:e}){return n.jsx("div",{className:"nav-menu-content-columns",children:e.columns.map((t,o)=>n.jsx(ot,{column:t},o))})}function ot({column:e}){return n.jsxs("div",{className:"nav-menu-column",children:[e.card&&n.jsxs(B,{href:e.card.href,className:"nav-menu-link-card gradient-hover-border gb-gradient--sky-could-orange",children:[n.jsx("h4",{className:"heading-04",children:e.card.label}),n.jsx("p",{children:e.card.description})]}),e.links&&n.jsxs("ul",{className:"nav-menu-link-list",children:[e.heading&&n.jsx("h3",{className:"nav-menu-column-heading",children:e.heading}),e.links.map(t=>n.jsx("li",{children:n.jsx(B,{href:t.href,className:"nav-content-link","data-astro-prefetch":t.prefetch,children:t.label})},t.label))]})]})}export{lt as NavMenu};

